name: ci
run-name: CI - Engine
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        cmake-version: ["3.26.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install conan
        run: pip install conan
      - name: Build project
        run: python3 build.py Release
      - name: Install .NET SDK on Windows
        run: |
          choco install dotnet-sdk --version 6.0.100
      - name: Download Dependency Walker
        if: runner.os == 'Windows'
        run: |
          curl -L -o depends.zip https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip
          unzip depends.zip -d depends
          mv depends/Dependencies.exe ./depends.exe
      - name: Check missing DLLs with Dependency Walker
        if: runner.os == 'Windows'
        run: |
          ./depends.exe /c "D:\a\Engine\Engine\build\pulsar-engine-test.exe" > missing_dlls.txt
          cat missing_dlls.txt
      - name: Test project
        run: ctest -C Release
