name: ci
run-name: CI - Engine
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10"]
        cmake-version: ["3.26.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ matrix.cmake-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install conan
        run: pip install conan
      - name: Build project
        run: python3 build.py Release
      - name: Install Vulkan SDK (Windows only)
        if: runner.os == 'Windows'
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - name: Check Vulkan DLL Presence
        run: |
          if not exist "%VULKAN_SDK%\\bin\\vulkan-1.dll" (
            echo "vulkan-1.dll is missing"
            exit 1
          ) else (
            echo "vulkan-1.dll is present"
          )
      - name: Test project
        run: ctest -C Release
